name: iOS CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      # 1. Get the source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Select Xcode
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      # 3. Show Xcode version
      - name: Check Xcode version
        run: xcodebuild -version

      # 4. Build the iOS project
      - name: Build iOS project
        run: |
          xcodebuild \
            -workspace CISwift.xcworkspace \
            -scheme Dev_UIKit \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_ALLOWED=NO \
            clean build
